WAV_FILES_PATH = "archive/free-spoken-digit-dataset-master/recordings"
DESIRED_SIZE = 4000
FILTER_BANKS = 32
WINDOW_SIZE = 25
STRIDE = 10
NO_OF_CLASSES = 10
RUNS_PATH = "./runs"
EXPERIMENT_NAME = "resnet_based_model_polyloss"

DATASET_PERCENTAGE = 1
TRAIN_TEST_SPLIT = 0.9

EPOCHS = 1000
BATCH_SIZE = 64
EPOCH_AFTER_SAVE_MODEL = 4
MODELS_TO_KEEP = 4
DEVICE = 0
LEARNING_RATE = 0.001

MODEL_PATH = "./pretrained_models"

RESUME_TRAIN = False
RESUME_TRAIN_PATH = ""
